[project]
name = "carbon-cycle-modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.6",
    "nbstripout>=0.9.1",
    "pandas-stubs>=3.0.0.260204",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "scipy-stubs>=1.17.1.4",
    "sphinx>=9.1.0",
]

[tool.ruff]
    # The maximum line length.
    line-length = 120

    [tool.ruff.lint]
    select = [
        "E",    # pycodestyle errors
        "W",    # pycodestyle warnings
        "F",    # pyflakes: Logical errors 
        "B",    # flake8-bugbear: Finding common "bugs".
        "C4",   # flake8-comprehensions
        "S",    # flake8-bandit: security issues.
        "SIM",  # flake8-simplify: Suggests refactors to make your code more readable. 
        "ARG",  # flake8-unused-arguments
        "TCH",  # flake8-type-checking (moves imports to TYPE_CHECKING blocks)
        "I",    # isort: Sorting your imports automatically.
        "UP",   # pyupgrade: suggestions (keeps your code modern).
        "D",    # pydocstyle: checks that docstring are done correctly.
        "ANN",  # Forces you to add type annotations to all functions.
        "NPY",  # Specific rules for NumPy.
        "PD",   # Specific rules for Pandas.
        "PT",   # Best practices for pytest, like ensuring you use @pytest.fixture correctly.
    ]

    ignore = [
        # Ignore D203 (one-blank-line-before-class) because it conflicts with D211 (no-blank-line-before-class)
        "D203",

        # Ignore D212 (multi-line-summary-first-line) because it conflicts with D213 (multi-line-summary-second-line) 
        "D212",

        # Ignore D400 (First line should end with a period) because it conflicts with 
        # D415 (First line should end with a period, question mark, or exclamation point) 
        "D400",
    ]

    [tool.ruff.format]
    quote-style = "double"
    indent-style = "space"
